[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'electronicparsers'
version = '1.0'
description = 'Collection of NOMAD parsers for electronic structure codes.'
readme = "README.md"
authors = [{ name = "The NOMAD Authors" }]
license = { file = "LICENSE" }
dependencies = [
    # "nomad-lab[infrastrucutre]",
    "lxml",
    "pyscf==2.0.1; sys_platform == 'darwin'",
    "matid",
    "netCDF4",
]

[project.urls]
homepage = "https://github.com/nomad-coe/electronic-parsers"

[project.optional-dependencies]
tests = [
    'mypy==0.730',
    'pylint==2.3.1',
    'pylint_plugin_utils==0.5',
    'pycodestyle',
    'pytest==3.10.0',
    'pytest-timeout',
    'pytest-cov==2.7.1',
]

[tool.setuptools.packages.find]
include = ["electronicparsers*"]

[tool.setuptools.package-data]
electronicparsers = ['*/metadata.yaml', '*/README.md']
